import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'

const faqs = [
  {
    q: "How do I connect my Shopify store?",
    a: "Go to Profile → click 'Connect with Shopify' → enter your store name → click OK → approve permissions on Shopify. Takes less than 60 seconds!"
  },
  {
    q: "How does the AI description generator work?",
    a: "Go to Product Optimizer → click on any product → click 'Generate AI Description'. Our AI analyzes your product title, type and price to write a compelling description optimized for conversions."
  },
  {
    q: "What is A/B Testing?",
    a: "A/B testing lets you test two versions of something (like a product description) to see which one converts better. Create a test, run it for 24-48 hours, and see which variant wins."
  },
  {
    q: "How are recommendations generated?",
    a: "Recommendations are generated by analyzing your real Shopify store data — products missing descriptions, low stock items, revenue opportunities, and more. They update automatically every time you refresh."
  },
  {
    q: "Is my store data secure?",
    a: "Yes! We use Shopify's official OAuth to connect your store. We never store your Shopify password. Your data is encrypted in transit and we never sell it to third parties."
  },
  {
    q: "How do I upgrade my plan?",
    a: "Go to Pricing & Billing in the sidebar → choose your plan → click 'Start free trial'. You get 14 days free on paid plans, no card charged today."
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes! You can cancel anytime from Pricing & Billing → Manage subscription. Your access continues until the end of the billing period."
  },
  {
    q: "Why is my dashboard showing $0?",
    a: "Make sure your Shopify store is connected in Profile settings. If it is, click the Refresh button or log out and log back in. Your store needs at least one order to show revenue data."
  },
]

export default function HelpPage() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const [openFaq, setOpenFaq] = useState(null)
  const [contactForm, setContactForm] = useState({ subject: '', message: '' })
  const [sent, setSent] = useState(false)
  const [sending, setSending] = useState(false)

  const handleContact = async (e) => {
    e.preventDefault()
    setSending(true)
    try {
      await fetch('/api/support/contact', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + localStorage.getItem('token')
        },
        body: JSON.stringify({
          email: user?.email,
          name: user?.name,
          subject: contactForm.subject,
          message: contactForm.message
        })
      })
      setSent(true)
    } catch {
      setSent(true) // Show success anyway
    } finally {
      setSending(false)
    }
  }

  return (
    <div style={{ maxWidth: 720 }}>
      <div style={{ marginBottom: 28 }}>
        <h1 style={{ fontSize: 22, fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.3px' }}>Help & Support</h1>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>Find answers or contact our team</p>
      </div>

      {/* Quick links */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 24 }}>
        {[
          { icon: '🚀', title: 'Getting Started', desc: 'Connect your store', action: () => navigate('/profile') },
          { icon: '🛍️', title: 'Products', desc: 'AI descriptions', action: () => navigate('/products') },
          { icon: '📊', title: 'Analytics', desc: 'View your data', action: () => navigate('/analytics') },
        ].map((item, i) => (
          <button key={i} onClick={item.action} style={{
            background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 10,
            padding: 16, cursor: 'pointer', textAlign: 'left', fontFamily: 'inherit',
            transition: 'border-color 0.2s'
          }}
          onMouseEnter={e => e.currentTarget.style.borderColor = 'var(--purple-light)'}
          onMouseLeave={e => e.currentTarget.style.borderColor = 'var(--border)'}
          >
            <div style={{ fontSize: 24, marginBottom: 8 }}>{item.icon}</div>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-primary)' }}>{item.title}</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>{item.desc}</div>
          </button>
        ))}
      </div>

      {/* FAQ */}
      <div className="card" style={{ padding: 24, marginBottom: 16 }}>
        <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 16 }}>❓ Frequently Asked Questions</div>
        {faqs.map((faq, i) => (
          <div key={i} style={{ borderBottom: i < faqs.length - 1 ? '1px solid var(--border)' : 'none' }}>
            <button
              onClick={() => setOpenFaq(openFaq === i ? null : i)}
              style={{
                width: '100%', padding: '12px 0', background: 'none', border: 'none',
                cursor: 'pointer', display: 'flex', justifyContent: 'space-between',
                alignItems: 'center', fontFamily: 'inherit', textAlign: 'left'
              }}
            >
              <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{faq.q}</span>
              <span style={{ color: 'var(--text-muted)', fontSize: 18, flexShrink: 0, marginLeft: 12 }}>
                {openFaq === i ? '−' : '+'}
              </span>
            </button>
            {openFaq === i && (
              <div style={{ fontSize: 13, color: 'var(--text-muted)', paddingBottom: 12, lineHeight: 1.6 }}>
                {faq.a}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Contact form */}
      <div className="card" style={{ padding: 24, marginBottom: 16 }}>
        <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 4 }}>📧 Contact Support</div>
        <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 16 }}>
          We typically respond within 24 hours at <strong>hello@optiviseai.io</strong>
        </div>

        {sent ? (
          <div style={{ background: 'var(--green-dim)', border: '1px solid var(--green)', borderRadius: 8, padding: '16px', textAlign: 'center' }}>
            <div style={{ fontSize: 24, marginBottom: 8 }}>✅</div>
            <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--green)' }}>Message sent!</div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4 }}>We'll get back to you within 24 hours.</div>
          </div>
        ) : (
          <form onSubmit={handleContact}>
            <div className="auth-field">
              <label>Subject</label>
              <input type="text" placeholder="What do you need help with?" value={contactForm.subject}
                onChange={e => setContactForm({...contactForm, subject: e.target.value})} required/>
            </div>
            <div className="auth-field">
              <label>Message</label>
              <textarea placeholder="Describe your issue in detail..."
                value={contactForm.message}
                onChange={e => setContactForm({...contactForm, message: e.target.value})}
                required rows={4}
                style={{
                  width: '100%', background: 'var(--bg-secondary)', border: '1px solid var(--border)',
                  borderRadius: 8, padding: '10px 12px', color: 'var(--text-primary)',
                  fontSize: 13, fontFamily: 'inherit', resize: 'vertical', outline: 'none',
                  boxSizing: 'border-box'
                }}
              />
            </div>
            <button type="submit" className="auth-btn-primary" disabled={sending}>
              {sending ? 'Sending...' : 'Send message →'}
            </button>
          </form>
        )}
      </div>

      {/* Contact info */}
      <div className="card" style={{ padding: 20, display: 'flex', gap: 24, flexWrap: 'wrap' }}>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 2 }}>EMAIL</div>
          <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--purple-light)' }}>hello@optiviseai.io</div>
        </div>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 2 }}>RESPONSE TIME</div>
          <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>Within 24 hours</div>
        </div>
        <div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 2 }}>PRIVACY POLICY</div>
          <a href="/privacy" style={{ fontSize: 13, fontWeight: 600, color: 'var(--purple-light)', textDecoration: 'none' }}>View policy →</a>
        </div>
      </div>
    </div>
  )
}