
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://db.ogcgznrojgdgrsymwosl.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=VEENAR@NI1967
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#  JWT
jwt.secret=optivise-super-secret-jwt-key-change-in-prod
jwt.expiration=86400000

# OpenAI
openai.api.key=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
openai.model=gpt-4o

#  Shopify
shopify.store.domain=ai-description-test-store-v.myshopify.com
shopify.store.access.token=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

# Stripe
stripe.secret.key=sk_test_51TPggF0vLRWUJW45GfaXGm2HCPKXmCjuCHqDxTvRwOQBl7ZPaunpGQHfPyy5HxA8r5VbfjmAZO1brQoXo1QEFnNi00c3HjrK0z
stripe.publishable.key=pk_test_51TPggF0vLRWUJW45nD4y81fiiFXizezXFCDvSLN6DUBhYldHUSVWlz3vSwnl35KbgsFkE2q2wp8OWA1azrwnPzws005TXuQQSK
stripe.webhook.secret=whsec_placeholder
stripe.price.starter.monthly=price_1TPhIy0vLRWUJW45yKZI8x00
stripe.price.growth.monthly=price_1TPhNu0vLRWUJW45ZmMcsWRj

#  CORS
cors.allowed-origins=http://localhost:5173,https://optivise-seven.vercel.app,https://*.vercel.app

# Logging
logging.level.com.optivise=INFO
logging.level.org.springframework.security=WARN

# Resend Email
resend.api.key=re_9ctqJLtQ_KPQKn9weUwUSvUA5qqJY6GZs
resend.from.email=hello@optiviseai.io

# Shopify OAuth
shopify.oauth.client.id=${SHOPIFY_CLIENT_ID:fdc1df617fb6ec77d357f3e3792fe670}
shopify.oauth.client.key=${SHOPIFY_CLIENT_KEY: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}
shopify.oauth.redirect.uri=https://www.optiviseai.io/api/auth/shopify/callback
# force rebuild Fri May 15 11:25:24 CDT 2026
# trigger rebuild Sun May 17 02:53:13 CDT 2026
