spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ogcgznrojgdgrsymwosl
spring.datasource.password=VEENAR@NI1967